---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wealthalloc-ingress
  namespace: wealthalloc
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.wealthalloc.com
    secretName: wealthalloc-tls
  rules:
  - host: api.wealthalloc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wealthalloc-api-service
            port:
              number: 80
